app/models/usuario.py
from app import db
from werkzeug.security import generate_password_hash, check_password_hash


class Usuario(db.Model):
    __tablename__='usuario'
    idUsuario = db.Column(db.Integer, primary_key=True)
    usuario=db.Column(db.String(256),nullable=True)
    contraseña=db.Column(db.String(256), nullable=True)
    nombreUsuario = db.Column(db.String(256), nullable=False)
    identificacionUsuario = db.Column(db.String(256), nullable=False)
    Facultad_idFacultad = db.Column(db.Integer, db.ForeignKey('facultad.idFacultad'), nullable=False)
    historiales = db.relationship('Historial', backref='usuario', lazy=True)
    #es_administrador = db.Column(db.Boolean, default=False)
        
    def __repr__(self):
        return f'{self.nombreUsuario}'

    def is_authenticated(self):
        return True  # Siempre devolvemos True porque todos los usuarios autenticados son válidos

    def is_active(self):
        return True  # Aquí puedes implementar lógica para desactivar cuentas de usuario si es necesario

    def is_anonymous(self):
        return False  # Devolvemos False porque los usuarios autenticados no son anónimos

    def get_id(self):
        return str(self.idUsuario)  # Devolvemos el ID del usuario como una cadena Unicode
    
    def set_password(self, password):
        self.contraseña = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.contraseña, password)

app/routes/equipo_routes.py
from flask import Blueprint, render_template, flash, request, redirect, url_for, jsonify
from app import db
from flask_login import (
    login_required,
    login_manager,
    UserMixin,
    login_user,
    logout_user,
    current_user,
)
from sqlalchemy.exc import IntegrityError
from sqlalchemy import or_
from datetime import datetime
from app.models import Equipo
from app.models import Historial
from app.models import Usuario
from app.models import Software
import socket
import json
import threading
from app.config import SERVER_HOST, SERVER_PORT

bp = Blueprint("equipo", __name__)

@bp.route("/equipo", methods=["GET", "POST"])
@login_required
def equipo():
    if request.method == "GET":
        usuario = current_user
        equipos = Equipo.query.all()
        software = Software.query.all()
        software_list = [{"idSoftware": s.idSoftware, "nombreSoftware": s.nombreSoftware} for s in software]
        return render_template(
            "administracion/equipo/main.html", usuario=usuario, equipos=equipos, software=software_list
        )


@bp.route("/equipo/pedir_equipo", methods=["GET", "POST"])
@login_required
def pedir_equipo():
    if request.method == "POST":
        data = request.get_json()
        pc = data.get('pc')
        software_seleccionado = request.form.get('software')
        software = data.get('softwareId')
        otroSoftware = data.get('otroSoftware')

        print("Datos recibidos:", data)
        try:
            noRepeatUser = Historial.query.filter(Historial.Usuario_idUsuario==current_user.idUsuario, Historial.horaFin==None).first()
            if noRepeatUser:
                return jsonify({"status": "warning", "message": "El usuario ya tiene asignado un equipo"})

            equipo = Equipo.query.filter_by(idEquipo=pc).first()
            equipo.estadoEquipo = "usado"
            if software_seleccionado==0:
                return jsonify({"status": "warning", "message": "Por favor selecciona un software"})
            else: 
                if otroSoftware is None:
                    registro = Historial(
                    Usuario_idUsuario=current_user.idUsuario,
                    horaInicio=datetime.now().strftime('%H:%M:%S'),
                    Equipo_idEquipo=pc,
                    nombreSala="D507",
                    software_idSoftware=software
                )
                else :
                    registro = Historial(
                    Usuario_idUsuario=current_user.idUsuario,
                    horaInicio=datetime.now().strftime('%H:%M:%S'),
                    Equipo_idEquipo=pc,
                    nombreSala="D507",
                    software_idSoftware=software,
                    otroSoftware=otroSoftware
                    )
            db.session.add(registro)
            db.session.add(equipo)
            db.session.commit()

        

            return jsonify({"status": "success", "message": f"Computador {pc} registrado y desbloqueado correctamente."})
        except IntegrityError as e:
            print("error en registro pc: ", e)
            db.session.rollback()
            return jsonify({"status": "error", "message": "Complete todos los campos"})


@bp.route("/equipo/estado_equipo", methods=["GET", "POST"])
def estado_equipo():
    if current_user.is_authenticated:
        if request.method == "POST":
            equipo_a_buscar = request.form.get('equipo')
            buscar = (
                db.session.query(Usuario.nombreUsuario, Usuario.identificacionUsuario, Equipo.idEquipo, Historial.horaInicio, Equipo.sala, Software.nombreSoftware, Historial.otroSoftware, Historial.Usuario_idUsuario, Historial.fecha)
                .join(Historial, Historial.Usuario_idUsuario == Usuario.idUsuario)
                .join(Equipo, Historial.Equipo_idEquipo == Equipo.idEquipo)
                .join(Software, Historial.software_idSoftware == Software.idSoftware)
                .filter(Historial.horaFin == None)
                .filter(or_(
                    Equipo.idEquipo==equipo_a_buscar,
                    Usuario.nombreUsuario.ilike(f"%{equipo_a_buscar}%"),
                    Usuario.identificacionUsuario==equipo_a_buscar
                    )
                )
                .order_by(Historial.fecha.desc(), Historial.horaInicio.desc())
                .all()
            )
            print("consulta para buscar",buscar)
            cantidadEquipos = len(buscar)
            return render_template("administracion/estadoEquipo/index.html", equipos_usados=buscar, cantidad_equipos=cantidadEquipos)
        else:
            equiposUsados = (
                db.session.query(Usuario.nombreUsuario, Usuario.identificacionUsuario, Equipo.idEquipo, Historial.horaInicio, Equipo.sala, Software.nombreSoftware, Historial.otroSoftware, Historial.Usuario_idUsuario, Historial.fecha)
                .join(Historial, Historial.Usuario_idUsuario == Usuario.idUsuario)
                .join(Equipo, Historial.Equipo_idEquipo == Equipo.idEquipo)
                .join(Software, Historial.software_idSoftware == Software.idSoftware)
                .filter(Historial.horaFin == None)
                .order_by(Historial.fecha.desc(), Historial.horaInicio.desc())
                .all()
            )
            print("informacion de la tabla",equiposUsados)
            cantidadEquipos = len(equiposUsados)
            return render_template("administracion/estadoEquipo/index.html", equipos_usados=equiposUsados, cantidad_equipos=cantidadEquipos)
    else:
        return redirect(url_for('usuario.login_administracion'))

@bp.route("/equipo/liberar_equipo/<int:idEquipo>", methods=["POST"])
def liberar_equipo(idEquipo):
    if current_user.is_authenticated:
        data = request.json  # Obtiene el cuerpo JSON de la petición
        idUsuario = data.get('idUsuario')  # Obtiene el idUsuario

        equipo_a_editar = Equipo.query.filter_by(idEquipo=idEquipo).first()
        editar_historial = Historial.query.filter_by(Usuario_idUsuario=idUsuario, Equipo_idEquipo=idEquipo, horaFin=None).first_or_404()

        # Actualizamos los campos
        equipo_a_editar.estadoEquipo = "libre"
        editar_historial.horaFin = datetime.now().strftime('%H:%M:%S') # Actualiza la hora

        try:
            db.session.commit()
            return jsonify({'success': True, 'message': 'Historial actualizado con la fecha y hora actuales.'})
        except Exception as e:
            db.session.rollback()  # Revertimos en caso de error
            print("error en la actualizacion: ", e)
            return jsonify({'success': False, 'message': 'Error al actualizar el historial.'})
    else:
        return jsonify({'success': False, 'message': 'No estás autenticado.'})

@bp.route("/equipo/liberar_todo/", methods=["POST"])
def liberar_todo():
    if current_user.is_authenticated:
        editar_historial_D507 = Historial.query.filter(Historial.horaFin==None, Equipo.sala=="D507").all()
        editar_equipo_D507 = Equipo.query.filter(Equipo.estadoEquipo=="usado", Equipo.sala=="D507").all()

        for equipo in editar_equipo_D507:
            equipo.estadoEquipo = "libre"

        # Actualizar los campos de cada equipo y registro del historial
        for historial in editar_historial_D507:
            historial.horaFin = datetime.now().strftime('%H:%M:%S')

        try:
            db.session.commit()  # Guardamos los cambios en la base de datos
            return jsonify({'success': True, 'message': 'Historial actualizado con la fecha y hora actuales.'})
        except Exception as e:
            db.session.rollback()  # Revertimos en caso de error
            print("error en la actualizacion: ", e)
            return jsonify({'success': False, 'message': 'Error al actualizar el historial.'})
    else:
        return jsonify({'success': False, 'message': 'No estás autenticado.'})

app/routes/usuario_routes.py
from flask import Blueprint, render_template, flash, request, redirect, url_for
from flask_login import (
    login_required,
    login_manager,
    UserMixin,
    login_user,
    logout_user,
    current_user,
)
from sqlalchemy.exc import IntegrityError
from sqlalchemy import or_
from werkzeug.security import check_password_hash, generate_password_hash
from flask import jsonify
from app import db, login_manager
from app.models.facultad import Facultad
from app.models.usuario import Usuario

bp = Blueprint("usuario", __name__)

@login_manager.unauthorized_handler
def unauthorized_callback():
    flash("Por favor inicia sesión para acceder a esta página.", "error")
    return redirect(url_for("usuario.login"))



@bp.route("/usuario", methods=['GET','POST'])
def indexUsuario():
    if current_user.is_authenticated:
        if request.method=='GET':
            usuarios = (db.session.query(Usuario.identificacionUsuario, Usuario.nombreUsuario, Facultad.nombreFacultad)
                        .join(Usuario, Usuario.Facultad_idFacultad==Facultad.idFacultad).all())
            return render_template('administracion/usuarios/usuarios.html',usuarios=usuarios)
        if request.method=='POST':
            usuario_a_buscar = request.form.get('usuario')
            usuarios = (
                db.session.query(Usuario.identificacionUsuario, Usuario.nombreUsuario, Facultad.nombreFacultad)
                .join(Facultad, Usuario.Facultad_idFacultad==Facultad.idFacultad)
                .filter(
                    or_(
                        Usuario.nombreUsuario.ilike(f"%{usuario_a_buscar}%"),
                        Usuario.identificacionUsuario == usuario_a_buscar,
                        Facultad.nombreFacultad.ilike(f"%{usuario_a_buscar}%")
                    )).all()
                )
            print("usuario a buscar",usuario_a_buscar)
            print("usuario busqueda",usuarios)
            return render_template('administracion/usuarios/usuarios.html',usuarios=usuarios)
    else:
        flash("Inicie sesion para continuar...", "error")
        return redirect(url_for('usuario.login_administracion'))



@bp.route("/register_usuario", methods=["GET", "POST"])
def register_usuario():
    if request.method == "GET":
        facultad = Facultad.query.all()
        return render_template("usuario/register_usuarios.html", facultad=facultad)
    
    if request.method == "POST":
        documento = request.form["documento"]
        nombre = request.form["nombre"]
        facultad = request.form.get('facultad')
        identificacionUsuario = Usuario.query.filter_by(identificacionUsuario=documento).count()

        if not facultad or not nombre:
            return {"status": "error", "message": "Complete todos los campos"}, 400
        elif identificacionUsuario > 0:
            return {"status": "warning", "message": "Identificación ya registrada"}, 400
        else:
            usuario = Usuario(
                usuario=None,
                contraseña=None,
                nombreUsuario=nombre,
                identificacionUsuario=documento,
                Facultad_idFacultad=facultad,
            )
            try:
                db.session.add(usuario)
                db.session.commit()
                usuarioActual = Usuario.query.filter_by(identificacionUsuario=documento).first()
                login_user(usuarioActual)
                return {"status": "success", "message": "Registro exitoso"}, 200
            except IntegrityError as e:
                db.session.rollback()
                return {"status": "error", "message": "Error en el registro"}, 400




@bp.route("/login_usuario", methods=["GET", "POST"])
def login_usuario():
    if request.method == "GET":
        return redirect(url_for('usuario.login'))
    if request.method == "POST":
        identificacion = request.form.get("documento")
        if identificacion:
            usuarioActual = Usuario.query.filter_by(
                identificacionUsuario=identificacion
            ).first()
            if usuarioActual:
                login_user(usuarioActual)
                return jsonify({"success": True, "redirect": url_for("equipo.equipo")})
            else:
                return jsonify({"success": False, "message": "Usted no está registrado en el sistema..."})
    return jsonify({"success": False, "message": "Error en la solicitud."})

    


@bp.route("/login")
def login():
    if request.method=="GET":
        return render_template("usuario/login_usuarios.html")
    
@bp.route("/login_administracion", methods=["GET","POST"])
def login_administracion():
    if request.method=="GET":
        return render_template("administracion/login_administracion.html")
    if request.method=="POST":
        usuario = request.form.get("usuario")
        contraseña = request.form.get("contraseña")
        user = Usuario.query.filter_by(usuario=usuario).first()
        #contraseña_hash = generate_password_hash(contraseña)
        #print(contraseña_hash)
        if user:
            
            if check_password_hash(user.contraseña, contraseña):
                login_user(user)
                print("current user:", current_user)
                return redirect(url_for('usuario.administracion'))
            else :
                flash("Ingrese la contraseña de administrador correcta.", "error")
                return redirect(url_for('usuario.login_administracion'))         
        else:
            flash("El usuario no existe.", "error")
            return redirect(url_for('usuario.login_administracion'))

@bp.route("/administracion", methods=["GET","POST"])
def administracion():
    if current_user.is_authenticated:
        if request.method=="GET":
            return render_template("administracion/administracion.html")
    else:
        flash("Inicie sesion para continuar...", "error")
        return redirect(url_for('usuario.login_administracion'))

        

@bp.route("/logout", methods=["POST"])
@login_required
def logout():
    logout_user()
    return redirect(url_for('index'))


@bp.route("/perfil", methods=["GET","POST"])
@login_required
def perfil():
    if request.method=="GET":
        return render_template("usuario/usuarios.html")

app/templates/usuario/login_usuarios.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <link rel="shortcut icon" href="{{ url_for('static', filename='../static/images/Logo-uexternado.png') }}">
  <link rel="stylesheet" href="{{url_for('static',filename='../static/dist/css/output.css')}}">
  <script src="https://kit.fontawesome.com/175f4319ea.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <script src="{{url_for('static', filename='../static/dist/js/numpad.js')}}"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body class="fondo bg-cover bg-no-repeat">
  <style>
    .fondo {
      background-image: url("{{ url_for('static', filename='images/externado1.jpg') }}");
    }
  </style>
  <header class="flex row bg-white max-h-32 justify-between items-center">
    <img src="{{url_for('static',filename='../static/images/logo-uec.png')}}" alt=""
      class="object-contain w-1/6 aspect-3/2 mx-4">
    <div>
      <ul class="navlist">
        <li>
          <a href="{{ url_for('index') }}"
            class="text-green-900 m-16 text-2xl font-semibold p-4 rounded-xl hover:text-green-800 hover:shadow-2xl"><i
              class="fa-solid fa-hand-point-left"></i> Volver</a>
        </li>
      </ul>
    </div>
  </header>

  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
  {% for category, message in messages %}
  <div class="mt-10 mx-5
                                {% if category == 'success' %}
                                bg-green-100 border border-green-400 text-green-700
                                {% elif category == 'error' %}
                                bg-red-100 border border-red-400 text-red-700
                                {% elif category == 'warning' %}
                                bg-yellow-100 border border-yellow-400 text-yellow-700
                                {% endif %}
                                px-4 py-3 rounded relative" role="alert">
    <strong class="font-bold">
      {% if category == 'success' %}
      Éxito:
      {% elif category == 'error' %}
      Error:
      {% elif category == 'warning' %}
      Advertencia:
      {% endif %}
    </strong>
    <span class="block sm:inline">{{ message }}</span>
  </div>
  {% endfor %}
  {% endif %}
  {% endwith %}


  <div class="flex justify-center m-24">
    <form action="{{ url_for('usuario.login_usuario') }}" class="bg-white max-w-lg  p-10 rounded-3xl shadow-2xl"
      method="post">
      <h2 class="text-4xl mb-4 text-center">Ingreso de usuarios sala D</h2>
      <p class="font-light text-lg text-center">Por favor ingresa los siguientes datos:</p>
      <div class="mt-8 grid gap-8">
        <div class="form__group">
          <input type="number" name="documento" id="password" class="form__input" placeholder=" " required>
          <label style="font-size: 1.2rem;" for="password" class="form__label">Documento</label>
          <span class="form__line"></span>
        </div>
        <input type="submit" class="form__submit" name="entrar" value="Entrar">
        <a href="{{ url_for('index') }}" class="form__submit__return">Volver</a>
        <!--ENLACE FORMULARIO REGISTRO -->
        <span class="login">¿Primera vez que ingresas?</span>
        <a href="{{ url_for('usuario.register_usuario')}}" class="form__submit_register">Registrarme</a>
      </div>

    </form>
  </div>
  <script>
    window.addEventListener("load", function () {
      numpad.attach({
        id: "password",
        readonly: false
      })
    })
  </script>
  <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
  <script>
    $("body").on("contextmenu", function (e) {
      return false;
    })
  </script>
  <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script>
  $(document).ready(function () {
    $("form").on("submit", function (event) {
      event.preventDefault(); // Evita el envío estándar del formulario

      $.ajax({
        type: "POST",
        url: $(this).attr("action"),
        data: $(this).serialize(),
        success: function (response) {
          if (response.success) {
            window.location.href = response.redirect; // Redirigir si es exitoso
          } else {
            Swal.fire({
              icon: 'error',
              title: 'Error',
              text: response.message,
            }).then(() => {
              window.location.href = "{{ url_for('usuario.register_usuario') }}"; // Redirige al usuario
          });
          }
        },
        error: function () {
          Swal.fire({
            icon: 'error',
            title: 'Error',
            text: 'Ocurrió un error en la solicitud.',
          });
        }
      });
    });
  });
</script>


</body>

</html>

app/templates/usuario/register_usuarios.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="{{ url_for('static', filename='../static/images/Logo-uexternado.png') }}">
    <link rel="stylesheet" href="{{url_for('static',filename='../static/dist/css/output.css')}}">
    <script src="https://kit.fontawesome.com/175f4319ea.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="{{url_for('static', filename='../static/dist/js/numpad.js')}}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
    <title>Document</title>
</head>

<body class="fondo bg-cover bg-no-repeat">
    <style>
        .fondo {
            background-image: url("{{ url_for('static', filename='images/externado1.jpg') }}");
        }
    </style>
    <header class="flex row bg-white max-h-32 justify-between items-center">
        <img src="{{url_for('static',filename='../static/images/logo-uec.png')}}" alt=""
            class="object-contain w-1/6 aspect-3/2 mx-4">
        <div>
            <ul class="navlist">
                <li>
                    <a href="{{ url_for('index') }}"
                        class="text-green-900 m-16 text-2xl font-semibold p-4 rounded-xl hover:text-green-800 hover:shadow-2xl"><i
                            class="fa-solid fa-hand-point-left"></i> Volver</a>
                </li>
            </ul>
        </div>
    </header>

    <div class="flex justify-center mt-20">
        <form id="registerForm" class="bg-white max-w-lg p-10 rounded-3xl shadow-2xl" method="post">
            <h2 class="text-4xl mb-4 text-center">Registro de Usuarios sala D</h2>
            <p class="font-light text-lg text-center">Por favor registra los siguientes datos:</p>

            <div class="mt-8 grid gap-8">
                <div class="form__group">
                    <input type="hidden" name="sala" value="">
                    <input type="number" id="documento" class="form__input" placeholder=" " name="documento" required>
                    <label style="font-size: 1.1rem;" for="documento" class="form__label">Documento</label>
                    <span class="form__line"></span>
                </div>
                <div class="form__group">
                    <input type="text" id="nombre" class="form__input" placeholder="Nombre Completo " name="nombre" required>
                </div>
                <div class="select" required>
                    <select name="facultad" class="format border-2 border-black" required>
                        <option selected disabled>Selecciona tu facultad</option>
                        {% for facultades in facultad %}
                        <option class="option" value="{{ facultades.idFacultad }}">
                            {{ facultades.nombreFacultad }}
                        </option>
                        {% endfor %}
                    </select>
                </div>
                <button type="submit" class="form__submit">Registrarme</button>
                <a href="{{ url_for('usuario.login') }}" class="form__submit__return">Volver</a>
            </div>
        </form>
    </div>

    <script>
        $(document).ready(function() {
            $('#registerForm').on('submit', function(e) {
                e.preventDefault(); // Evita el envío normal del formulario

                $.ajax({
                    type: "POST",
                    url: "{{ url_for('usuario.register_usuario') }}",
                    data: $(this).serialize(), // Serializa los datos del formulario
                    success: function(response) {
                        // Si el registro fue exitoso
                        Swal.fire({
                            icon: 'success',
                            title: 'Éxito',
                            text: response.message
                        }).then(() => {
                            window.location.href = "{{ url_for('equipo.equipo') }}"; // Redirige al usuario
                        });
                    },
                    error: function(xhr) {
                        const response = xhr.responseJSON; // Obtiene la respuesta JSON del error
                        Swal.fire({
                            icon: response.status === 'warning' ? 'warning' : 'error',
                            title: response.status.charAt(0).toUpperCase() + response.status.slice(1),
                            text: response.message
                        });
                    }
                });
            });
        });
    </script>

    <script>
            window.addEventListener("load", function () {
                numpad.attach({
                    id: "documento",
                    readonly: false
                })
            })
        </script>
        <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
        <script>
            $("body").on("contextmenu", function (e) {
                return false;
            })
        </script>
</html>