app/models/software.py
from app import db

class Software(db.Model):
    __tablename__ = 'software'
    idSoftware = db.Column(db.Integer, primary_key=True, nullable=False)
    nombreSoftware =  db.Column(db.String(100), nullable=False)
    historiales = db.relationship('Historial', backref='software', lazy=True)

app/routes/software_routes.py
from flask import Blueprint, render_template, flash, request, jsonify,redirect, url_for
from flask_login import (
    login_required,
    login_manager,
    UserMixin,
    login_user,
    logout_user,
    current_user,
)
from sqlalchemy.exc import IntegrityError
from app import db, login_manager
from app.models import Software
bp = Blueprint("software", __name__)

@bp.route("/software",  methods=["GET"])
def indexSoftware():
    if current_user.is_authenticated:
        if request.method=="GET":
            softwares = Software.query.all()
            print("softwares: ", softwares)
            return render_template("/administracion/software/index.html", software=softwares)
    else:
        flash("Inicie sesion para continuar...", "error")
        return redirect(url_for('usuario.login_administracion'))
    
@bp.route("/software/eliminar", methods=["POST"])
def eliminar_software():
    if current_user.is_authenticated:
        if request.method == "POST":
            data = request.get_json()  # Recibir los datos en JSON
            idSoftware = data.get("idSoftware")  # Obtener el ID del software
            
            # Buscar el software por su ID
            software = Software.query.filter_by(idSoftware=idSoftware).first()
            
            if software:
                try:
                    db.session.delete(software)  # Eliminar el registro
                    db.session.commit()  # Confirmar los cambios
                    return jsonify({"status": "success", "message": f"Software eliminado correctamente."})
                except Exception as e:
                    db.session.rollback()  # Revertir los cambios si ocurre un error
                    return jsonify({"status": "error", "message": f"Error al eliminar software: {str(e)}"})
            else:
                return jsonify({"status": "error", "message": f"Software con ID {idSoftware} no encontrado."})
    
        
@bp.route("/software/nuevo", methods=["POST"])
def nuevo_software():
    if current_user.is_authenticated:
        if request.method == "POST":
            data = request.get_json()  # Recibir los datos en JSON
            nombreSoftware = data.get("nombreSoftware")  # Obtener el nombre del software
            software = Software.query.filter_by(nombreSoftware=nombreSoftware).first()
            if not software:
                try:
                    software = Software(nombreSoftware=nombreSoftware)
                    db.session.add(software)
                    db.session.commit()
                    return jsonify({"status": "success", "message": f"Software agregado correctamente."})
                except Exception as e:
                    db.session.rollback()
                    return jsonify({"status": "error", "message": f"Error al agregar software "})
            else:
                return jsonify({"status": "error", "message": f"El software {nombreSoftware}  ya existe."})

app/templates/administracion/software/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <link rel="shortcut icon" href="{{ url_for('static', filename='../static/images/Logo-uexternado.png') }}" />
    <link rel="stylesheet" href="{{url_for('static',filename='../static/dist/css/output.css')}}" />
    <script src="https://kit.fontawesome.com/175f4319ea.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
</head>

<body>
    <!--inicio nav-->
    <header class="flex row bg-white max-h-32 justify-between items-center">
        <img src="{{url_for('static',filename='../static/images/logo-uec.png')}}" alt=""
            class="object-contain w-1/6 aspect-3/2 mx-4" />
            <ul class="navlist">
                <li>
                    <a href="{{ url_for('usuario.administracion') }}"
                        class="text-green-900 m-16 text-2xl font-semibold p-4 rounded-xl hover:text-green-800 hover:shadow-2xl"><i
                            class="fa-solid fa-hand-point-left"></i> Volver</a>
                </li>
            </ul>
    </header>
    <!--fin nav-->

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="mt-10 mx-5
                    {% if category == 'success' %}
                        bg-green-100 border border-green-400 text-green-700
                    {% elif category == 'error' %}
                        bg-red-100 border border-red-400 text-red-700
                    {% elif category == 'warning' %}
                        bg-yellow-100 border border-yellow-400 text-yellow-700
                    {% endif %}
                px-4 py-3 rounded relative" role="alert">
                    <strong class="font-bold">
                        {% if category == 'success' %}
                            Éxito:
                        {% elif category == 'error' %}
                            Error:
                        {% elif category == 'warning' %}
                            Advertencia:
                        {% endif %}
                    </strong>
                    <span class="block sm:inline">{{ message }}</span>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    
    

    <div id="contenedor" class="bg-slate-100 rounded-2xl max-w-7xl flex flex-col m-auto my-10">
        <div class="bg-green-600 opacity-95 rounded-xl flex flex-row shadow-lg justify-evenly items-center py-4">
            <p class="text-slate-100 text-3xl font-normal font-sans">
                Software Licenciado
            </p>
        </div>
        <div class="bg-white shadow-md p-10 rounded-b-xl">
            <div class="form__group my-5 flex flex-row">
                <input type="text" name="usuario" id="search-input" class="form__input" autofocus placeholder=" " required>
                <label style="font-size: 1.2rem;" for="search-input" class="form__label">Busqueda</label>
                <span class="form__line"></span>
                <button class="text-white rounded-lg text-center px-5 mx-5" style="background-color: rgba(0, 46, 25, .8);" id="liberar_todos">Añadir Nuevo Software</button>
            </div>
            <!-- Tabla que se ajusta al contenido -->
            <div id="tabla">
                    <div class="not-prose relative rounded-xl bg-slate-100">
                        <div style="background-position:10px 10px" class="absolute inset-0 bg-grid-slate-100 [mask-image:linear-gradient(0deg,#fff,rgba(255,255,255,0.6))] dark:bg-grid-slate-700/25 dark:[mask-image:linear-gradient(0deg,rgba(255,255,255,0.1),rgba(255,255,255,0.5))]"></div>
                            <div class="relative rounded-xl">
                                <div class="shadow-sm my-8">
                                    <table class="border-collapse table-auto w-full text-sm">
                                        <thead>
                                            <th class="border-b border-slate-300 p-4 pl-4 text-slate-500 text-left">Software</th>
                                            <td class="border-b border-slate-300 p-4 pr-8 text-slate-500">
                                                Accion
                                            </td> <!-- Botones -->
                                        </thead>
                                        <tbody id="usuarios-tbody" class="bg-slate-100">
                                            {% for el_software in software %}
                                            {% if el_software.idSoftware != 200 %}
                                            <tr>
                                                <input type="hidden" value="{{ el_software.idSoftware }}" class="idSoftware">
                                                <td class="border-b border-slate-300 p-4 pl-4 text-slate-500">{{ el_software.nombreSoftware }}</td>
                                                <td class="documento border-b border-slate-300 p-4 pl-4 text-slate-500">
                                                    <button class="eliminar-btn text-white rounded-lg text-center liberar-btn" style="background-color: rgba(0, 46, 25, .8);">
                                                        <p class="p-2 text-sm">Eliminar</p>
                                                    </button>
                                                </td><!-- Botones -->
                                            </tr>
                                            {% endif %}
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        <div class="absolute inset-0 pointer-events-none border border-black/5 rounded-xl dark:border-white/5"></div>
                    </div>
            </div>
        </div>
    </div>
    <script>
        document.getElementById("liberar_todos").addEventListener("click", function () {
            Swal.fire({
                title: 'Añadir Nuevo Software',
                html: `
                    <input type="text" id="nombreSoftware" class="swal2-input" placeholder="Nombre del Software">
                `,
                showCancelButton: true,
                confirmButtonText: 'Añadir',
                cancelButtonText: 'Cancelar',
                preConfirm: () => {
                    const nombreSoftware = document.getElementById('nombreSoftware').value;
                    if (!nombreSoftware) {
                        Swal.showValidationMessage('Por favor ingresa el nombre del software');
                    }
                    return nombreSoftware;
                }
            }).then((result) => {
                if (result.isConfirmed) {
                    // Aquí puedes hacer la petición para enviar los datos al servidor
                    fetch("/software/nuevo", {
                        method: "POST",
                        headers: {
                            "Content-Type": "application/json"
                        },
                        body: JSON.stringify({
                            nombreSoftware: result.value
                        })
                    })
                    .then(response => response.json())
                    .then(data => {
                        if (data.status === 'success') {
                            Swal.fire({
                                icon: 'success',
                                title: '¡Éxito!',
                                text: data.message,
                                confirmButtonText: 'OK'
                            }).then(() => {
                                window.location.reload();  // Recargar la página para ver el nuevo software añadido
                            });
                        } else {
                            Swal.fire({
                                icon: 'error',
                                title: 'Error',
                                text: data.message
                            });
                        }
                    })
                    .catch(error => {
                        Swal.fire({
                            icon: 'error',
                            title: 'Error',
                            text: 'Ocurrió un error en la petición'
                        });
                    });
                }
            });
        });



        document.addEventListener("DOMContentLoaded", function () {
            const eliminarBtns = document.querySelectorAll(".eliminar-btn");
        
            eliminarBtns.forEach((btn) => {
                btn.addEventListener("click", function (event) {
                    event.preventDefault();  // Prevenir el comportamiento por defecto del botón
        
                    const idSoftware = this.closest("tr").querySelector(".idSoftware").value;
                    
                    fetch("/software/eliminar", {
                        method: "POST",
                        headers: {
                            "Content-Type": "application/json"
                        },
                        body: JSON.stringify({
                            idSoftware: idSoftware
                        })
                    })
                    .then(response => response.json())
                    .then(data => {
                        if (data.status == 'success') {
                            Swal.fire({
                                icon: 'success',
                                title: '¡Éxito!',
                                text: data.message,
                                confirmButtonText: 'OK'
                            }).then(() => {
                                // Redirige después de cerrar la alerta
                                window.location.href = `{{ url_for('software.indexSoftware') }}`;
                            });
                        } else {
                            Swal.fire({
                                icon: 'error',
                                title: 'Error',
                                text: data.message,
                                confirmButtonText: 'OK'
                            }).then(()=>{
                                window.location.href =  `{{ url_for('software.indexSoftware') }}`;
                            });
                        }
                    })
                    .catch(error => {
                        Swal.fire({
                            icon: 'error',
                            title: 'Error',
                            text: 'Ocurrió un error en la petición',
                            confirmButtonText: 'OK'
                        });
                    });
                });
            });
        });
    </script>
    
</body>

</html>