app/routes/accion_routes.py
from flask import Blueprint, render_template, request, jsonify, redirect,url_for
from app import db
from app.models import Equipo
from flask_login import (
    login_required,
    login_manager,
    UserMixin,
    login_user,
    logout_user,
    current_user,
)
from sqlalchemy.exc import IntegrityError

bp = Blueprint("accion", __name__)  

@login_required
@bp.route("/accion", methods=["GET","POST"])
def redireccion():
        accion = request.form.get('action')
        if accion == "facultades":
            return redirect("https://www.uexternado.edu.co/facultades/")
        elif accion == "historial":
            return redirect(url_for('historial.indexHistorial'))
        elif accion == "estadoEquipo":
            return redirect(url_for('equipo.estado_equipo'))
        elif accion == "usuarios":
            return redirect(url_for('usuario.indexUsuario'))
        elif accion == "software":
            return redirect(url_for('software.indexSoftware'))
        




@bp.route("/D507")
def D507():
    page = request.args.get('page', 1, type=int)
    per_page = 10

    # Calcular el número de elementos a omitir y limitar el número de elementos
    offset = (page - 1) * per_page
    equipos_query = Equipo.query.filter_by(sala="D507").offset(offset).limit(per_page).all()

    # Contar el total de elementos para calcular la paginación
    total = Equipo.query.filter_by(sala="D507").count()

    return render_template("/prueba/salaD507.html", equipos=equipos_query, page=page, per_page=per_page, total=total)



@bp.route("/D507_data")
def D507_data():
    page = request.args.get('page', 1, type=int)
    per_page = 10
    search = request.args.get('search', '', type=str)
    estado = request.args.get('estado', '', type=str)

    # Calcular el número de elementos a omitir y limitar el número de elementos
    offset = (page - 1) * per_page

    # Construir la consulta con las condiciones adicionales
    query = Equipo.query.filter_by(sala="D507")
    if search:
        query = query.filter(Equipo.idEquipo.ilike(f"%{search}%"))
    if estado:
        query = query.filter_by(estadoEquipo=estado)

    equipos_query = query.offset(offset).limit(per_page).all()
    total = query.count()

    items = [{'idEquipo': e.idEquipo, 'estadoEquipo': e.estadoEquipo} for e in equipos_query]

    return jsonify({
        'items': items,
        'total': total,
        'page': page,
        'per_page': per_page,
        'has_prev': page > 1,
        'has_next': page * per_page < total,
        'prev_num': page - 1 if page > 1 else None,
        'next_num': page + 1 if page * per_page < total else None
    })
    
    
@bp.route("/H405")
def H405():
    page = request.args.get('page', 1, type=int)
    per_page = 10

    offset = (page - 1) * per_page
    equipos_query = Equipo.query.filter_by(sala="H405").offset(offset).limit(per_page).all()
    total = Equipo.query.filter_by(sala="H405").count()

    return render_template("/prueba/salaH405.html", equipos=equipos_query, page=page, per_page=per_page, total=total)


@bp.route("/H405_data")
def H405_data():
    page = request.args.get('page', 1, type=int)
    per_page = 10
    search = request.args.get('search', '', type=str)
    estado = request.args.get('estado', '', type=str)

    offset = (page - 1) * per_page

    query = Equipo.query.filter_by(sala="H405")
    if search:
        query = query.filter(Equipo.idEquipo.ilike(f"%{search}%"))
    if (estado):
        query = query.filter_by(estadoEquipo=estado)

    equipos_query = query.offset(offset).limit(per_page).all()
    total = query.count()

    items = [{'idEquipo': e.idEquipo, 'estadoEquipo': e.estadoEquipo} for e in equipos_query]

    return jsonify({
        'items': items,
        'total': total,
        'page': page,
        'per_page': per_page,
        'has_prev': page > 1,
        'has_next': page * per_page < total,
        'prev_num': page - 1 if page > 1 else None,
        'next_num': page + 1 if page * per_page < total else None
    })

@bp.route("/I408")
def I408():
    page = request.args.get('page', 1, type=int)
    per_page = 10

    offset = (page - 1) * per_page
    equipos_query = Equipo.query.filter_by(sala="I408").offset(offset).limit(per_page).all()
    total = Equipo.query.filter_by(sala="I408").count()

    return render_template("/prueba/salaI408.html", equipos=equipos_query, page=page, per_page=per_page, total=total)


@bp.route("/I408_data")
def I408_data():
    page = request.args.get('page', 1, type=int)
    per_page = 10
    search = request.args.get('search', '', type=str)
    estado = request.args.get('estado', '', type=str)

    offset = (page - 1) * per_page

    query = Equipo.query.filter_by(sala="I408")
    if search:
        query = query.filter(Equipo.idEquipo.ilike(f"%{search}%"))
    if (estado):
        query = query.filter_by(estadoEquipo=estado)

    equipos_query = query.offset(offset).limit(per_page).all()
    total = query.count()

    items = [{'idEquipo': e.idEquipo, 'estadoEquipo': e.estadoEquipo} for e in equipos_query]

    return jsonify({
        'items': items,
        'total': total,
        'page': page,
        'per_page': per_page,
        'has_prev': page > 1,
        'has_next': page * per_page < total,
        'prev_num': page - 1 if page > 1 else None,
        'next_num': page + 1 if page * per_page < total else None
    })



@bp.route("/celular")
def celular():
    return render_template("prueba/prueba_diseño_celular.html")

@bp.route("/computo")
def computo():
    return render_template("prueba/computo.html")

app/routes/usuario_routes.py
from flask import Blueprint, render_template, flash, request, redirect, url_for
from flask_login import (
    login_required,
    login_manager,
    UserMixin,
    login_user,
    logout_user,
    current_user,
)
from sqlalchemy.exc import IntegrityError
from sqlalchemy import or_
from werkzeug.security import check_password_hash, generate_password_hash
from flask import jsonify
from app import db, login_manager
from app.models.facultad import Facultad
from app.models.usuario import Usuario

bp = Blueprint("usuario", __name__)

@login_manager.unauthorized_handler
def unauthorized_callback():
    flash("Por favor inicia sesión para acceder a esta página.", "error")
    return redirect(url_for("usuario.login"))



@bp.route("/usuario", methods=['GET','POST'])
def indexUsuario():
    if current_user.is_authenticated:
        if request.method=='GET':
            usuarios = (db.session.query(Usuario.identificacionUsuario, Usuario.nombreUsuario, Facultad.nombreFacultad)
                        .join(Usuario, Usuario.Facultad_idFacultad==Facultad.idFacultad).all())
            return render_template('administracion/usuarios/usuarios.html',usuarios=usuarios)
        if request.method=='POST':
            usuario_a_buscar = request.form.get('usuario')
            usuarios = (
                db.session.query(Usuario.identificacionUsuario, Usuario.nombreUsuario, Facultad.nombreFacultad)
                .join(Facultad, Usuario.Facultad_idFacultad==Facultad.idFacultad)
                .filter(
                    or_(
                        Usuario.nombreUsuario.ilike(f"%{usuario_a_buscar}%"),
                        Usuario.identificacionUsuario == usuario_a_buscar,
                        Facultad.nombreFacultad.ilike(f"%{usuario_a_buscar}%")
                    )).all()
                )
            print("usuario a buscar",usuario_a_buscar)
            print("usuario busqueda",usuarios)
            return render_template('administracion/usuarios/usuarios.html',usuarios=usuarios)
    else:
        flash("Inicie sesion para continuar...", "error")
        return redirect(url_for('usuario.login_administracion'))



@bp.route("/register_usuario", methods=["GET", "POST"])
def register_usuario():
    if request.method == "GET":
        facultad = Facultad.query.all()
        return render_template("usuario/register_usuarios.html", facultad=facultad)
    
    if request.method == "POST":
        documento = request.form["documento"]
        nombre = request.form["nombre"]
        facultad = request.form.get('facultad')
        identificacionUsuario = Usuario.query.filter_by(identificacionUsuario=documento).count()

        if not facultad or not nombre:
            return {"status": "error", "message": "Complete todos los campos"}, 400
        elif identificacionUsuario > 0:
            return {"status": "warning", "message": "Identificación ya registrada"}, 400
        else:
            usuario = Usuario(
                usuario=None,
                contraseña=None,
                nombreUsuario=nombre,
                identificacionUsuario=documento,
                Facultad_idFacultad=facultad,
            )
            try:
                db.session.add(usuario)
                db.session.commit()
                usuarioActual = Usuario.query.filter_by(identificacionUsuario=documento).first()
                login_user(usuarioActual)
                return {"status": "success", "message": "Registro exitoso"}, 200
            except IntegrityError as e:
                db.session.rollback()
                return {"status": "error", "message": "Error en el registro"}, 400




@bp.route("/login_usuario", methods=["GET", "POST"])
def login_usuario():
    if request.method == "GET":
        return redirect(url_for('usuario.login'))
    if request.method == "POST":
        identificacion = request.form.get("documento")
        if identificacion:
            usuarioActual = Usuario.query.filter_by(
                identificacionUsuario=identificacion
            ).first()
            if usuarioActual:
                login_user(usuarioActual)
                return jsonify({"success": True, "redirect": url_for("equipo.equipo")})
            else:
                return jsonify({"success": False, "message": "Usted no está registrado en el sistema..."})
    return jsonify({"success": False, "message": "Error en la solicitud."})

    


@bp.route("/login")
def login():
    if request.method=="GET":
        return render_template("usuario/login_usuarios.html")
    
@bp.route("/login_administracion", methods=["GET","POST"])
def login_administracion():
    if request.method=="GET":
        return render_template("administracion/login_administracion.html")
    if request.method=="POST":
        usuario = request.form.get("usuario")
        contraseña = request.form.get("contraseña")
        user = Usuario.query.filter_by(usuario=usuario).first()
        #contraseña_hash = generate_password_hash(contraseña)
        #print(contraseña_hash)
        if user:
            
            if check_password_hash(user.contraseña, contraseña):
                login_user(user)
                print("current user:", current_user)
                return redirect(url_for('usuario.administracion'))
            else :
                flash("Ingrese la contraseña de administrador correcta.", "error")
                return redirect(url_for('usuario.login_administracion'))         
        else:
            flash("El usuario no existe.", "error")
            return redirect(url_for('usuario.login_administracion'))

@bp.route("/administracion", methods=["GET","POST"])
def administracion():
    if current_user.is_authenticated:
        if request.method=="GET":
            return render_template("administracion/administracion.html")
    else:
        flash("Inicie sesion para continuar...", "error")
        return redirect(url_for('usuario.login_administracion'))

        

@bp.route("/logout", methods=["POST"])
@login_required
def logout():
    logout_user()
    return redirect(url_for('index'))


@bp.route("/perfil", methods=["GET","POST"])
@login_required
def perfil():
    if request.method=="GET":
        return render_template("usuario/usuarios.html")

app/templates/administracion/administracion.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <link rel="shortcut icon" href="{{ url_for('static', filename='../static/images/Logo-uexternado.png') }}" />
    <link rel="stylesheet" href="{{url_for('static',filename='../static/dist/css/output.css')}}" />
    <script src="https://kit.fontawesome.com/175f4319ea.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
</head>

<body>
    <!--inicio nav-->
    <header class="flex row bg-white max-h-32 justify-between items-center">
        <img src="{{url_for('static',filename='../static/images/logo-uec.png')}}" alt=""
            class="object-contain w-1/6 aspect-3/2 mx-4" />
        <form action="{{ url_for('usuario.logout') }}" method="post">
            <ul class="navlist">
                <li>
                    <button class="text-green-900 m-16 text-2xl font-semibold p-4 rounded-xl hover:text-green-800 hover:shadow-2xl"><i
                            class="fa-solid fa-hand-point-left"></i> Salir</button>
                </li>
            </ul>
        </form>
    </header>
    <!--fin nav-->
    <!-- FIN HEADER -->
    <!-- INICIO CARDS -->

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="mt-10 mx-5
                                {% if category == 'success' %}
                                bg-green-100 border border-green-400 text-green-700
                                {% elif category == 'error' %}
                                bg-red-100 border border-red-400 text-red-700
                                {% elif category == 'warning' %}
                                bg-yellow-100 border border-yellow-400 text-yellow-700
                                {% endif %}
                                px-4 py-3 rounded relative" role="alert">
        <strong class="font-bold">
            {% if category == 'success' %}
            Éxito:
            {% elif category == 'error' %}
            Error:
            {% elif category == 'warning' %}
            Advertencia:
            {% endif %}
        </strong>
        <span class="block sm:inline">{{ message }}</span>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}


    <div class="m-auto fondo bg-cover bg-no-repeat">
        <div class="text-center flex justify-around h-screen bg-cover bg-center box-border ">
            <div class="flex h-5/6 items-center">
                <div>
                    <style>
                        .fondo {
                            background-image: url("{{ url_for('static', filename='images/salasc_externado.jpeg') }}");
                        }

                        .card2 {
                            background-image: url("{{ url_for('static', filename='images/universidad_facultades.webp') }}")
                        }

                        .card3 {
                            background-image: url("{{ url_for('static', filename='images/registros.jpg') }}")
                        }

                        .card4 {
                            background-image: url("{{ url_for('static', filename='images/representantes-estudiantiles-2021-1.webp') }}")
                        }

                        .card5 {
                            background-image: url("{{ url_for('static', filename='images/equipos_estado_pc.jpg') }}")
                        }
                    </style>
                    <div>
                        <h1 class="text-7xl my-5">
                            Administrador <i class="fa-solid fa-user-shield"></i>
                        </h1>
                    </div>
                    <form class="flex row justify-evenly" action="{{ url_for('accion.redireccion') }}" method="POST">
                        <div class="card card2 shadow-xl" onclick="">
                            <button class="btn-card" name="action" value="software">
                                <h5>Software</h5>
                                <p>Software de la Universidad.</p>
                            </button>
                        </div>

                        <div class="card card3 shadow-xl" onclick="">
                            <button class="btn-card" name="action" value="historial">
                                <h5>Historial</h5>
                                <p>Historial estudiantes salas de software.</p>
                            </button>
                        </div>
                    </form>

                    <form class="flex row justify-evenly" action="{{ url_for('accion.redireccion') }}" method="POST">
                        <div class="card card4 shadow-xl" onclick="">
                            <button class="btn-card" name="action" value="usuarios">
                                <h5>Usuarios</h5>
                                <p>Usuarios registrados.</p>
                            </button>
                        </div>

                        <div class="card card5 shadow-xl" onclick="">
                            <button class="btn-card" name="action" value="estadoEquipo">
                                <h5>Estado PC</h5>
                                <p>Disponibilidad equipos en salas de software.</p>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- FIN CARDS -->
</body>

</html>

app/templates/administracion/login_administracion.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <link rel="shortcut icon" href="{{ url_for('static', filename='../static/images/Logo-uexternado.png') }}">
  <link rel="stylesheet" href="{{url_for('static',filename='../static/dist/css/output.css')}}">
  <script src="https://kit.fontawesome.com/175f4319ea.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <script src="{{url_for('static', filename='../static/dist/js/numpad.js')}}"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body class="fondo bg-cover bg-no-repeat">
  <style>
    .fondo {
      background-image: url("{{ url_for('static', filename='images/externado1.jpg') }}");
    }
  </style>
  <header class="flex row bg-white max-h-32 justify-between items-center">
    <img src="{{url_for('static',filename='../static/images/logo-uec.png')}}" alt=""
      class="object-contain w-1/6 aspect-3/2 mx-4">
    <div>
      <ul class="navlist">
        <li>
          <a href="{{ url_for('index') }}"
            class="text-green-900 m-16 text-2xl font-semibold p-4 rounded-xl hover:text-green-800 hover:shadow-2xl"><i
              class="fa-solid fa-hand-point-left"></i> Volver</a>
        </li>
      </ul>
    </div>
  </header>

  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
  {% for category, message in messages %}
  <div class="mt-10 mx-5
                                {% if category == 'success' %}
                                bg-green-100 border border-green-400 text-green-700
                                {% elif category == 'error' %}
                                bg-red-100 border border-red-400 text-red-700
                                {% elif category == 'warning' %}
                                bg-yellow-100 border border-yellow-400 text-yellow-700
                                {% endif %}
                                px-4 py-3 rounded relative" role="alert">
    <strong class="font-bold">
      {% if category == 'success' %}
      Éxito:
      {% elif category == 'error' %}
      Error:
      {% elif category == 'warning' %}
      Advertencia:
      {% endif %}
    </strong>
    <span class="block sm:inline">{{ message }}</span>
  </div>
  {% endfor %}
  {% endif %}
  {% endwith %}


  <div class="flex justify-center m-24">
    <form action="{{ url_for('usuario.login_administracion') }}" class="bg-white max-w-lg  p-10 rounded-3xl shadow-2xl"
      method="post">
      <h2 class="text-4xl mb-4 text-center">Ingreso ADMINISTRADOR</h2>
      <p class="font-light text-lg text-center">Por favor ingresa los siguientes datos:</p>
      <div class="mt-8 grid gap-8">
        <div class="form__group">
          <input type="text" name="usuario" id="usuario" class="form__input" placeholder=" " required>
          <label style="font-size: 1.2rem;" for="usuario" class="form__label">Usuario</label>
          <span class="form__line"></span>
        </div>
        <div class="form__group">
          <input type="password" name="contraseña" id="contraseña" class="form__input" placeholder=" " required>
          <label style="font-size: 1.2rem;" for="contraseña" class="form__label">Contraseña</label>
          <span class="form__line"></span>
        </div>
        <input type="submit" class="form__submit" name="entrar" value="Entrar">
        <a href="{{ url_for('index') }}" class="form__submit__return">Volver</a>
      </div>

    </form>
  </div>
</body>

</html>